# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: event.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='event.proto',
  package='nsq_utils',
  syntax='proto3',
  serialized_pb=_b('\n\x0b\x65vent.proto\x12\tnsq_utils\"+\n\rCustomedEvent\x12\x0c\n\x04path\x18\x01 \x01(\t\x12\x0c\n\x04\x62ody\x18\x02 \x01(\t\"1\n\x0f\x43ommonEventBody\x12\x11\n\tsub_event\x18\x01 \x01(\t\x12\x0b\n\x03key\x18\x02 \x01(\t\"\xa9\x01\n\x0b\x43ommonEvent\x12\x0e\n\x06\x61ppkey\x18\x01 \x01(\t\x12\x10\n\x08\x65vent_id\x18\x02 \x01(\t\x12\x11\n\ttimestamp\x18\x03 \x01(\x05\x12\x35\n\x08\x64\x61ta_map\x18\x04 \x03(\x0b\x32#.nsq_utils.CommonEvent.DataMapEntry\x1a.\n\x0c\x44\x61taMapEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\xd7\x01\n\x0bJuniorEvent\x12\x13\n\x0b\x64istinct_id\x18\x01 \x01(\t\x12\x0f\n\x07project\x18\x02 \x01(\t\x12\x0c\n\x04type\x18\x03 \x01(\t\x12\x11\n\ttimestamp\x18\x04 \x01(\x03\x12\x12\n\nevent_name\x18\x05 \x01(\t\x12:\n\nproperties\x18\x06 \x03(\x0b\x32&.nsq_utils.JuniorEvent.PropertiesEntry\x1a\x31\n\x0fPropertiesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x62\x06proto3')
)




_CUSTOMEDEVENT = _descriptor.Descriptor(
  name='CustomedEvent',
  full_name='nsq_utils.CustomedEvent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='path', full_name='nsq_utils.CustomedEvent.path', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='body', full_name='nsq_utils.CustomedEvent.body', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=69,
)


_COMMONEVENTBODY = _descriptor.Descriptor(
  name='CommonEventBody',
  full_name='nsq_utils.CommonEventBody',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sub_event', full_name='nsq_utils.CommonEventBody.sub_event', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='key', full_name='nsq_utils.CommonEventBody.key', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=71,
  serialized_end=120,
)


_COMMONEVENT_DATAMAPENTRY = _descriptor.Descriptor(
  name='DataMapEntry',
  full_name='nsq_utils.CommonEvent.DataMapEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='nsq_utils.CommonEvent.DataMapEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='nsq_utils.CommonEvent.DataMapEntry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=_descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001')),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=246,
  serialized_end=292,
)

_COMMONEVENT = _descriptor.Descriptor(
  name='CommonEvent',
  full_name='nsq_utils.CommonEvent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='appkey', full_name='nsq_utils.CommonEvent.appkey', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='event_id', full_name='nsq_utils.CommonEvent.event_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='nsq_utils.CommonEvent.timestamp', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data_map', full_name='nsq_utils.CommonEvent.data_map', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_COMMONEVENT_DATAMAPENTRY, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=123,
  serialized_end=292,
)


_JUNIOREVENT_PROPERTIESENTRY = _descriptor.Descriptor(
  name='PropertiesEntry',
  full_name='nsq_utils.JuniorEvent.PropertiesEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='nsq_utils.JuniorEvent.PropertiesEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='nsq_utils.JuniorEvent.PropertiesEntry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=_descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001')),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=461,
  serialized_end=510,
)

_JUNIOREVENT = _descriptor.Descriptor(
  name='JuniorEvent',
  full_name='nsq_utils.JuniorEvent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='distinct_id', full_name='nsq_utils.JuniorEvent.distinct_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='project', full_name='nsq_utils.JuniorEvent.project', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='type', full_name='nsq_utils.JuniorEvent.type', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='nsq_utils.JuniorEvent.timestamp', index=3,
      number=4, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='event_name', full_name='nsq_utils.JuniorEvent.event_name', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='properties', full_name='nsq_utils.JuniorEvent.properties', index=5,
      number=6, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_JUNIOREVENT_PROPERTIESENTRY, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=295,
  serialized_end=510,
)

_COMMONEVENT_DATAMAPENTRY.containing_type = _COMMONEVENT
_COMMONEVENT.fields_by_name['data_map'].message_type = _COMMONEVENT_DATAMAPENTRY
_JUNIOREVENT_PROPERTIESENTRY.containing_type = _JUNIOREVENT
_JUNIOREVENT.fields_by_name['properties'].message_type = _JUNIOREVENT_PROPERTIESENTRY
DESCRIPTOR.message_types_by_name['CustomedEvent'] = _CUSTOMEDEVENT
DESCRIPTOR.message_types_by_name['CommonEventBody'] = _COMMONEVENTBODY
DESCRIPTOR.message_types_by_name['CommonEvent'] = _COMMONEVENT
DESCRIPTOR.message_types_by_name['JuniorEvent'] = _JUNIOREVENT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CustomedEvent = _reflection.GeneratedProtocolMessageType('CustomedEvent', (_message.Message,), dict(
  DESCRIPTOR = _CUSTOMEDEVENT,
  __module__ = 'event_pb2'
  # @@protoc_insertion_point(class_scope:nsq_utils.CustomedEvent)
  ))
_sym_db.RegisterMessage(CustomedEvent)

CommonEventBody = _reflection.GeneratedProtocolMessageType('CommonEventBody', (_message.Message,), dict(
  DESCRIPTOR = _COMMONEVENTBODY,
  __module__ = 'event_pb2'
  # @@protoc_insertion_point(class_scope:nsq_utils.CommonEventBody)
  ))
_sym_db.RegisterMessage(CommonEventBody)

CommonEvent = _reflection.GeneratedProtocolMessageType('CommonEvent', (_message.Message,), dict(

  DataMapEntry = _reflection.GeneratedProtocolMessageType('DataMapEntry', (_message.Message,), dict(
    DESCRIPTOR = _COMMONEVENT_DATAMAPENTRY,
    __module__ = 'event_pb2'
    # @@protoc_insertion_point(class_scope:nsq_utils.CommonEvent.DataMapEntry)
    ))
  ,
  DESCRIPTOR = _COMMONEVENT,
  __module__ = 'event_pb2'
  # @@protoc_insertion_point(class_scope:nsq_utils.CommonEvent)
  ))
_sym_db.RegisterMessage(CommonEvent)
_sym_db.RegisterMessage(CommonEvent.DataMapEntry)

JuniorEvent = _reflection.GeneratedProtocolMessageType('JuniorEvent', (_message.Message,), dict(

  PropertiesEntry = _reflection.GeneratedProtocolMessageType('PropertiesEntry', (_message.Message,), dict(
    DESCRIPTOR = _JUNIOREVENT_PROPERTIESENTRY,
    __module__ = 'event_pb2'
    # @@protoc_insertion_point(class_scope:nsq_utils.JuniorEvent.PropertiesEntry)
    ))
  ,
  DESCRIPTOR = _JUNIOREVENT,
  __module__ = 'event_pb2'
  # @@protoc_insertion_point(class_scope:nsq_utils.JuniorEvent)
  ))
_sym_db.RegisterMessage(JuniorEvent)
_sym_db.RegisterMessage(JuniorEvent.PropertiesEntry)


_COMMONEVENT_DATAMAPENTRY.has_options = True
_COMMONEVENT_DATAMAPENTRY._options = _descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001'))
_JUNIOREVENT_PROPERTIESENTRY.has_options = True
_JUNIOREVENT_PROPERTIESENTRY._options = _descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001'))
# @@protoc_insertion_point(module_scope)
